[package]
name = "diplopod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
bevy_prototype_lyon = "0.4.0"
rand = "0.8.4"
